kind: Service
apiVersion: v1
metadata:
  name: hellonode-service-deployment
spec:
  type: NodePort
  selector:
    app: hellonode-service
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 31000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellonode-service-deployment
  labels:
    app: hellonode-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellonode-service
  template:
    metadata:
      labels:
        app: hellonode-service
    spec:
      containers:
      - name: hellonode-service
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
